examples/AuctionHouseCRUD/AuctionHouse/Controllers/SellerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AuctionHouse.Models;
using AuctionHouse.DAL.Abstract;

namespace AuctionHouse.Controllers
{
    public class SellerController : Controller
    {
        private readonly ISellerRepository _sellerRepository;

        public SellerController(ISellerRepository sellerRepo)
        {
            _sellerRepository = sellerRepo;
        }

        // GET: Seller
        public IActionResult Index()
        {
            var sellers = _sellerRepository.GetAll().ToList();
            return View(sellers);
        }

        // GET: Seller/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seller = _sellerRepository.FindById(id.Value);  // NOTE: this will NOT load navigation properties
            if (seller == null)
            {
                return NotFound();
            }

            return View(seller);
        }

        // GET: Seller/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Seller/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FirstName,LastName,Email,Phone,TaxIdnumber")] Seller seller)
        {
            if (ModelState.IsValid)
            {
                if(_sellerRepository.TaxIdAlreadyInUse(seller.TaxIdnumber))
                {
                    ModelState.AddModelError("TaxIdnumber", "The Tax ID entered is invalid.  Please enter your correct ID.");
                    return View(seller);
                }
                try
                {
                    // AddOrUpdate in our repository calls SaveChanges
                    // the PK should already be 0 because we didn't bind it, but if we're creating a new one then it must be
                    // the default value for the given type (int = 0, string = null, etc.) or else the AddOrUpdate will try to perform 
                    // an update instead of an insert.  Just to be sure future changes don't cause a bug, we'll explicitly set it here
                    seller.Id = default(int);
                    // This is also where you can perform anything else needed server-side prior to creating the new Seller
                    _sellerRepository.AddOrUpdate(seller);
                }
                catch(DbUpdateConcurrencyException e)
                {
                    ViewBag.Message = "A concurrency error occurred while trying to add a new Seller.  Please try again.";
                    return View(seller);
                }
                catch(DbUpdateException e)
                {
                    ViewBag.Message = "An unknown database error occurred while trying to add a new Seller.  Please try again.";
                    return View(seller);
                }
                return RedirectToAction(nameof(Index));
            }
            // NOTE: if we get here, the model state is invalid and we need to redisplay the form
            return View(seller);
        }

        // GET: Seller/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seller = _sellerRepository.FindById(id.Value);
            if (seller == null)
            {
                return NotFound();
            }
            return View(seller);
        }

        // POST: Seller/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,FirstName,LastName,Email,Phone,TaxIdnumber")] Seller seller)
        {
            // Now we do want to bind the Id coming in so we can use it to compare to the one from the query string
            if (id != seller.Id || !_sellerRepository.Exists(seller.Id))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Here's your chance to do anything that might need to be done prior to updating
                    var existingSeller = _sellerRepository.FindById(seller.Id);
                    existingSeller.FirstName = seller.FirstName;
                    existingSeller.LastName = seller.LastName;
                    existingSeller.Email = seller.Email;
                    existingSeller.Phone = seller.Phone;
                    // existingSeller.TaxIdnumber = seller.TaxIdnumber;    // let's say this one requires some other validation before updating so we won't do it here for example
                    _sellerRepository.AddOrUpdate(existingSeller);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_sellerRepository.Exists(seller.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;  // I left this as the template produced it.  Returns 5xx Server Error in this case.  Basically
                                // meaning you will have to figure out what to do based on what your app is doing if we get to this point
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(seller);
        }

        // GET: Seller/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seller = _sellerRepository.FindById(id.Value);
            if (seller == null)
            {
                return NotFound();
            }

            return View(seller);
        }

        // POST: Seller/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var seller = _sellerRepository.FindById(id);
            if(seller == null)
            {
                return NotFound();
            }

            if (seller != null)
            {
                try
                {
                    _sellerRepository.Delete(seller);
                }
                catch(Exception e)
                {
                    throw;      // same here, you decide what makes sense here based on your app
                }
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

examples/AuctionHouseCRUD/AuctionHouse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuctionHouse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuctionHouse.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AuctionHouse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seller" asp-action="Index">Sellers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manage" asp-action="Index">Manage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AuctionHouse - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>