examples/Standups8/Standups/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Standups.Controllers.ActionFilters;
using Standups.DAL.Abstract;
using Standups.Data;
using Standups.Models;
using Standups.Services;
using Standups.ViewModels;

namespace Standups.Controllers
{
    public class MeetingsController : Controller
    {
        private IUserService _userService;
        private readonly IRepository<Supmeeting> _meetingRepository;
        private readonly IRepository<Supuser> _userRepository;

        public MeetingsController(IRepository<Supmeeting> meetingRepository, IRepository<Supuser> userRepository)
        {
            _meetingRepository = meetingRepository;
            _userRepository = userRepository;
        }

        [ServiceFilter(typeof(UserServiceFilter))]
        public IActionResult Index()
        {
            _userService.User = User;
            Supuser user = _userService.GetCurrentSupuser();
            
            // Get all meetings for this user
            List<Supmeeting> meetings = user.Supmeetings.OrderByDescending(m => m.SubmissionDate).ToList();

            MeetingsVM vm = new MeetingsVM
            {
                CurrentUser = user,
                Meetings = meetings
            };

            return View(vm);
        }

        [ServiceFilter(typeof(UserServiceFilter))]
        public IActionResult Details(int? id)
        {
            _userService.User = User;
            if (id == null)
            {
                return NotFound();
            }
            int mid = (int)id;
            Supuser user = _userService.GetCurrentSupuser();
            Supmeeting meeting = user.Supmeetings.Where(m => m.Id == mid).FirstOrDefault();

            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }

        [ServiceFilter(typeof(UserServiceFilter))]
        public IActionResult Create()
        {
            _userService.User = User;
            Supuser user = _userService.GetCurrentSupuser();

            Supmeeting mtg = new Supmeeting { Supuser = user };
            return View(mtg);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(UserServiceFilter))]
        public IActionResult Create([Bind("Completed,Planning,Obstacles")] Supmeeting supmeeting)
        {
            _userService.User = User;
            Supuser user = _userService.GetCurrentSupuser();
            if (ModelState.IsValid)
            {
                supmeeting.Supuser = user;
                supmeeting.SupuserId = user.Id;
                supmeeting.SubmissionDate = DateTime.UtcNow;
                _meetingRepository.AddOrUpdate(supmeeting);

                return RedirectToAction(nameof(Index));
            }
            Supmeeting mtg = new Supmeeting 
            { 
                Supuser = user, 
                Completed = supmeeting.Completed, 
                Planning = supmeeting.Planning, 
                Obstacles = supmeeting.Obstacles 
            };
            return View(mtg);
        }
    }
}

examples/Standups8/Standups/Views/Meetings/Create.cshtml
@model Standups.Models.Supmeeting

@{
    ViewBag.Title = "Create meeting report";
    Model.ReadOnly = false;
}

<div class="row justify-content-center">
    <div class="col text-center">
        <h1>Stand-Up Meeting <span class="fs-4">Report Form</span></h1>
        <hr />
    </div>
</div>

<div class="container-fluid">
    @using (Html.BeginForm("Create", "Meetings", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="mb-3">
            @Html.Partial("_ReportDetailsPartial", Model)
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    }
    <div>
        @Html.ActionLink("Back to All Reports", "Index")
    </div>
</div>

examples/Standups8/Standups/Views/Meetings/Details.cshtml
@model Standups.Models.Supmeeting

@{
    ViewBag.Title = "SUP Meeting Form";
    Model.ReadOnly = true;
}

<div class="row justify-content-center">
    <div class="col text-center">
        <h1>Stand-Up Meeting <span class="fs-4">Report</span></h1>
        <hr />
    </div>
</div>

<div class="container-fluid">
    @Html.Partial("_ReportDetailsPartial", Model)
    <div>
        @Html.ActionLink("Back to All Reports", "Index")
    </div>
</div>

examples/Standups8/Standups/Views/Meetings/Index.cshtml
@model Standups.ViewModels.MeetingsVM

@{
    ViewBag.Title = "Past Standup Meeting Reports";
}

@section HeadContent
    {
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
}

@section Scripts
    {
    <script>
        $(document).ready(function () {
            //console.log("running datatables...");
            $('#reports_table').DataTable();
        });
    </script>
}

<div >
    <div class="row justify-content-center">
        <div class="col text-center">
            <h1>Stand-Up Meeting <span class="fs-4">Reports</span></h1>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-4">
            <h2 class="">@Model.CurrentUser.FullName</h2>
        </div>
        <div class="col-xs-12 col-md-8">
            @if (Model.NumberOfReports == 0)
            {
                <p>You don't have any standup meeting reports yet.</p>
            }
            else
            {
                <table class="table table-striped" id="reports_table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>
                                @Html.DisplayNameFor(model => model.Meetings.FirstOrDefault().SubmissionDate)
                            </th>
                            <th>Day</th>
                            <th>
                                @Html.DisplayNameFor(model => model.Meetings.FirstOrDefault().Completed)
                            </th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Meetings)
                        {
                            <tr>
                                <td>
                                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                                </td>
                                <td>
                                    @item.TimeStampInPacificTimeZone.ToString("MM/dd/yyyy @ H:mm") @item.PSTorPDT
                                </td>
                                @if (item.TimeStampMeetsCriteria(Model.classtime, Model.classdays))
                                {
                                    <td class="success">@item.DayOfWeekString</td>
                                }
                                else
                                {
                                    <td class="info">@item.DayOfWeekString</td>
                                }
                                <td>
                                    @Html.DisplayFor(modelItem => item.Completed)
                                </td>

                            </tr>
                        }
                    </tbody>
                </table>
            }
            <p>
                @Html.ActionLink("Create New Report", "Create")
            </p>
        </div>
    </div>
</div>